branches:
  only:
    - master
git:
  quiet: true
  depth: false
jobs:
  include:
    - name: "Android Main Build"
      language: android
      os: linux
      dist : trusty
      addons:
        apt:
          packages:
            - autoconf
            - automake
            - libtool
            - pkg-config
            - curl
            - git
            - cmake
            - gcc
            - gperf
            - texinfo
            - yasm
            - bison
            - autogen
            - patch
      android:
        components:
          - tools
          - platform-tools
          - build-tools-32.0.0
          - android-32
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
      install:
        - echo y | sdkmanager "cmake;3.22.1"
      before_install:
        - yes | sdkmanager "cmake;3.22.1"
        - touch $HOME/.android/repositories.cfg
      before_script:
        - export ANDROID_NDK_ROOT=${ANDROID_HOME}ndk/21.3.6528147
        - rm -f ./build.log
        - wget https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/nasm-2.14.02.tar.gz;tar zxvf nasm-2.14.02.tar.gz;cd nasm-2.14.02;./configure;make;sudo make install;cd ..
      after_success:
        - grep -e INFO ./build.log | grep build
      after_failure:
        - tail -30 ./build.log
        - tail -30 ./src/ffmpeg/ffbuild/config.log
      script:
        - bash ./android.sh --no-output-redirection -d
    - name: "Android LTS Build"
      language: android
      os: linux
      dist : trusty
      addons:
        apt:
          packages:
            - autoconf
            - automake
            - libtool
            - pkg-config
            - curl
            - git
            - cmake
            - gcc
            - gperf
            - texinfo
            - yasm
            - bison
            - autogen
            - patch
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-16
          - android-21
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
      install:
#        - echo y | sdkmanager "ndk;21.3.6528147"
        - echo y | sdkmanager "cmake;3.22.1"
      before_install:
        - touch $HOME/.android/repositories.cfg'
        - yes | sdkmanager "cmake;3.22.1"
      before_script:
        - export ANDROID_NDK_ROOT=${ANDROID_HOME}ndk/21.3.6528147
        - rm -f ./build.log
        - wget https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/nasm-2.14.02.tar.gz;tar zxvf nasm-2.14.02.tar.gz;cd nasm-2.14.02;./configure;make;sudo make install;cd ..
      after_success:
        - grep -e INFO ./build.log | grep build
      after_failure:
        - tail -30 ./build.log
        - tail -30 ./src/ffmpeg/ffbuild/config.log
      script:
        - bash ./android.sh --lts --no-output-redirection -d